import type { WeaponArchetype } from '../content/gear/Items'
import {
  BASIC_ATTACK_ARROW_DEFINITION_ID,
  BASIC_ATTACK_ORB_DEFINITION_ID,
} from '../content/projectiles/Projectiles'
import type {
  BasicAttackVariantDefinition,
  SkillDefinition,
  SkillId,
} from '../content/skills/SkillConfigs'

export const BASIC_ATTACK_SKILL_ID: SkillId = 'basic-attack'
export const WHIRLWIND_SKILL_ID: SkillId = 'whirlwind'
export const CHAIN_LIGHTNING_SKILL_ID: SkillId = 'chain-lightning'
export const VITALITY_SKILL_ID: SkillId = 'vitality'
export const RAISE_SKELETON_SKILL_ID: SkillId = 'raise-skeleton'
export const FIERY_TOUCH_SKILL_ID: SkillId = 'fiery-touch'
export const DEFAULT_SKILL_SLOT_COUNT = 5
export const SKILL_REMOVAL_CHANCE = 0.05

export const BASIC_ATTACK_VARIANTS = {
  sword: {
    id: 'sword',
    description: 'Sweeps a wide melee arc through enemies in front of you.',
    kind: 'area',
    tags: ['physical', 'melee', 'area'],
    swingArcDegrees: 100,
    effectLifetime: 0.14,
    visual: {
      kind: 'area',
      icon: '🗡',
      primaryColor: '#f97316',
      secondaryColor: '#fdba74',
      outlineColor: '#ffedd5',
    },
  },
  bow: {
    id: 'bow',
    description: 'Fires arrows in a wide spread toward the current target.',
    kind: 'projectile',
    tags: ['physical', 'projectile'],
    projectileDefinitionId: BASIC_ATTACK_ARROW_DEFINITION_ID,
    spreadDegrees: 15,
    maxExtraProjectiles: 4,
    effectLifetime: 0.12,
    visual: {
      kind: 'projectile',
      icon: '➶',
      primaryColor: '#84cc16',
      secondaryColor: '#bef264',
      outlineColor: '#ecfccb',
      trailLength: 22,
      trailWidth: 3,
      projectileShape: 'arrow',
    },
  },
  wand: {
    id: 'wand',
    description: 'Launches seeking bolts in a wide spread toward a living target.',
    kind: 'projectile',
    tags: ['physical', 'projectile'],
    projectileDefinitionId: BASIC_ATTACK_ORB_DEFINITION_ID,
    spreadDegrees: 30,
    maxExtraProjectiles: 4,
    effectLifetime: 0.12,
    visual: {
      kind: 'projectile',
      icon: '✦',
      primaryColor: '#22d3ee',
      secondaryColor: '#a855f7',
      outlineColor: '#e0f2fe',
      trailLength: 16,
      trailWidth: 5,
      projectileShape: 'orb',
    },
  },
  staff: {
    id: 'staff',
    description: 'Creates a 40-unit area hit that poisons every enemy it strikes for 4 seconds. Each poison stack deals 50% of the applying hit physical and chaos damage per second.',
    kind: 'area',
    tags: ['physical', 'area', 'dot'],
    areaShape: 'circle',
    areaRadius: 40,
    poisonApplication: {
      durationSeconds: 4,
      physicalChaosRatio: 0.5,
    },
    effectLifetime: 0.16,
    visual: {
      kind: 'area',
      icon: '✦',
      primaryColor: '#a855f7',
      secondaryColor: '#d8b4fe',
      outlineColor: '#f3e8ff',
    },
  },
} as const satisfies Record<WeaponArchetype, BasicAttackVariantDefinition>

export const SKILL_DEFINITIONS = {
  [BASIC_ATTACK_SKILL_ID]: {
    id: BASIC_ATTACK_SKILL_ID,
    name: 'Basic Attack',
    description: 'Automatically attacks with your equipped weapon archetype.',
    kind: 'projectile',
    tags: ['physical', 'projectile'],
    cooldown: 1,
    baseDamage: { physical: 0 },
    damagePerLevel: {},
    projectileDefinitionId: BASIC_ATTACK_ORB_DEFINITION_ID,
    effectLifetime: 0.12,
    visual: {
      kind: 'projectile',
      icon: '✦',
      primaryColor: '#22d3ee',
      secondaryColor: '#a855f7',
      outlineColor: '#e0f2fe',
      trailLength: 16,
      trailWidth: 5,
      projectileShape: 'orb',
    },
  },
  [WHIRLWIND_SKILL_ID]: {
    id: WHIRLWIND_SKILL_ID,
    name: 'Whirlwind',
    description: 'Periodically damages every enemy close to you.',
    kind: 'area',
    tags: ['physical', 'melee', 'area'],
    cooldown: 2.5,
    baseDamage: { physical: 8 },
    damagePerLevel: {},
    radius: 90,
    effectLifetime: 0.2,
    visual: {
      kind: 'area',
      icon: '⟳',
      primaryColor: '#a78bfa',
      secondaryColor: '#c4b5fd',
      outlineColor: '#ede9fe',
    },
  },
  [CHAIN_LIGHTNING_SKILL_ID]: {
    id: CHAIN_LIGHTNING_SKILL_ID,
    name: 'Chain Lightning',
    description: 'Strikes a nearby enemy, then jumps to two distinct targets.',
    kind: 'chain',
    tags: ['lightning', 'area'],
    cooldown: 3.5,
    baseDamage: { lightning: 7 },
    damagePerLevel: {},
    maxRange: 260,
    jumpRange: 150,
    maxTargets: 3,
    effectLifetime: 0.18,
    visual: {
      kind: 'chain',
      icon: '⚡',
      primaryColor: '#22d3ee',
      secondaryColor: '#fef08a',
      outlineColor: '#cffafe',
      nodeRadius: 10,
    },
  },
  [VITALITY_SKILL_ID]: {
    id: VITALITY_SKILL_ID,
    name: 'Vitality',
    description: 'Automatically restores 2 HP every 5 seconds. Each level adds 2 HP per cast.',
    kind: 'utility',
    tags: ['defensive'],
    cooldown: 5,
    baseDamage: {},
    damagePerLevel: {},
    baseHealing: 2,
    healingPerLevel: 2,
    effectLifetime: 0.3,
    visual: {
      kind: 'utility',
      icon: '♥',
      primaryColor: '#22c55e',
      secondaryColor: '#86efac',
      outlineColor: '#dcfce7',
    },
  },
  [RAISE_SKELETON_SKILL_ID]: {
    id: RAISE_SKELETON_SKILL_ID,
    name: 'Raise Skeleton',
    description: 'Summons a persistent skeleton that attacks nearby enemies.',
    kind: 'utility',
    tags: ['physical', 'summon'],
    cooldown: 5,
    baseDamage: {},
    damagePerLevel: {},
    summonBaseDamage: 6,
    summonDamageIncreasePercentPerLevel: 8,
    summonBaseMaxHp: 10,
    summonMaxHpPerLevel: 5,
    summonAttackCooldown: 1,
    summonAttackRange: 70,
    summonBaseMaxCount: 1,
    effectLifetime: 0.3,
    visual: {
      kind: 'utility',
      icon: '☠',
      primaryColor: '#c084fc',
      secondaryColor: '#e9d5ff',
      outlineColor: '#f5f3ff',
    },
  },
  [FIERY_TOUCH_SKILL_ID]: {
    id: FIERY_TOUCH_SKILL_ID,
    name: 'Fiery Touch',
    description: 'Direct hits ignite the struck enemy, damaging nearby enemies.',
    kind: 'area',
    tags: ['fire', 'area', 'trigger'],
    cooldown: 2,
    baseDamage: { fire: 10 },
    damagePerLevel: { fire: 5 },
    radius: 80,
    effectLifetime: 0.24,
    visual: {
      kind: 'area',
      icon: '🔥',
      primaryColor: '#f97316',
      secondaryColor: '#facc15',
      outlineColor: '#fff7ed',
    },
  },
} as const satisfies Record<SkillId, SkillDefinition>
