import type {
  InventoryItemCategory,
  InventoryItemDefinition,
} from './InventoryTypes'

export const INVENTORY_ITEM_ID_PATTERN = /^[a-z0-9]+(?:-[a-z0-9]+)*$/

export const INVENTORY_ITEM_DEFINITIONS = {
  'basic-bait': {
    id: 'basic-bait',
    name: 'Basic Bait',
    flavorText: null,
    category: 'bait',
    rarity: 'common',
    stackable: false,
    maxStackSize: 1,
    tradeable: false,
    bindOnEquip: false,
    unlimited: true,
    salvageEssence: 0,
  },
  'river-worm': {
    id: 'river-worm',
    name: 'River Worm',
    flavorText: null,
    category: 'bait',
    rarity: 'uncommon',
    stackable: true,
    maxStackSize: 99,
    tradeable: true,
    bindOnEquip: false,
    unlimited: false,
    salvageEssence: 0,
  },
  'glow-grub': {
    id: 'glow-grub',
    name: 'Glow Grub',
    flavorText: null,
    category: 'bait',
    rarity: 'rare',
    stackable: true,
    maxStackSize: 99,
    tradeable: true,
    bindOnEquip: false,
    unlimited: false,
    salvageEssence: 0,
  },
  'moonwater-lure': {
    id: 'moonwater-lure',
    name: 'Moonwater Lure',
    flavorText: null,
    category: 'bait',
    rarity: 'epic',
    stackable: true,
    maxStackSize: 99,
    tradeable: true,
    bindOnEquip: false,
    unlimited: false,
    salvageEssence: 0,
  },
  'river-minnow': {
    id: 'river-minnow',
    name: 'River Minnow',
    flavorText: null,
    category: 'fish',
    stackable: false,
    maxStackSize: 1,
    tradeable: true,
    bindOnEquip: false,
    unlimited: false,
    salvageEssence: 2,
  },
  'reed-darter': {
    id: 'reed-darter',
    name: 'Reed Darter',
    flavorText: null,
    category: 'fish',
    stackable: false,
    maxStackSize: 1,
    tradeable: true,
    bindOnEquip: false,
    unlimited: false,
    salvageEssence: 2,
  },
  'glassfin-trout': {
    id: 'glassfin-trout',
    name: 'Glassfin Trout',
    flavorText: null,
    category: 'fish',
    stackable: false,
    maxStackSize: 1,
    tradeable: true,
    bindOnEquip: false,
    unlimited: false,
    salvageEssence: 2,
  },
  'silver-perch': {
    id: 'silver-perch',
    name: 'Silver Perch',
    flavorText: null,
    category: 'fish',
    stackable: false,
    maxStackSize: 1,
    tradeable: true,
    bindOnEquip: false,
    unlimited: false,
    salvageEssence: 5,
  },
  'lantern-pike': {
    id: 'lantern-pike',
    name: 'Lantern Pike',
    flavorText: null,
    category: 'fish',
    stackable: false,
    maxStackSize: 1,
    tradeable: true,
    bindOnEquip: false,
    unlimited: false,
    salvageEssence: 5,
  },
  'moon-carp': {
    id: 'moon-carp',
    name: 'Moon Carp',
    flavorText: null,
    category: 'fish',
    stackable: false,
    maxStackSize: 1,
    tradeable: true,
    bindOnEquip: false,
    unlimited: false,
    salvageEssence: 10,
  },
  'tideback-catfish': {
    id: 'tideback-catfish',
    name: 'Tideback Catfish',
    flavorText: null,
    category: 'fish',
    stackable: false,
    maxStackSize: 1,
    tradeable: true,
    bindOnEquip: false,
    unlimited: false,
    salvageEssence: 10,
  },
  'revival-koi': {
    id: 'revival-koi',
    name: 'Revival Koi',
    flavorText: null,
    category: 'fish',
    stackable: false,
    maxStackSize: 1,
    tradeable: true,
    bindOnEquip: false,
    unlimited: false,
    salvageEssence: 20,
  },
  'comet-eel': {
    id: 'comet-eel',
    name: 'Comet Eel',
    flavorText: null,
    category: 'fish',
    stackable: false,
    maxStackSize: 1,
    tradeable: true,
    bindOnEquip: false,
    unlimited: false,
    salvageEssence: 20,
  },
  'star-koi': {
    id: 'star-koi',
    name: 'Star Koi',
    flavorText: null,
    category: 'fish',
    stackable: false,
    maxStackSize: 1,
    tradeable: true,
    bindOnEquip: false,
    unlimited: false,
    salvageEssence: 40,
  },
  'starter-fishing-rod': {
    id: 'starter-fishing-rod',
    name: 'Wooden rod',
    flavorText: "It's actually just a stick with some spare yarn attached to the end",
    category: 'rod',
    rarity: 'common',
    stackable: false,
    maxStackSize: 1,
    tradeable: true,
    bindOnEquip: true,
    unlimited: false,
    salvageEssence: 1,
  },
  'silverline-fishing-rod': {
    id: 'silverline-fishing-rod',
    name: 'Silverline rod',
    flavorText: 'Threaded with real silver wire, or something close enough to shine.',
    category: 'rod',
    rarity: 'uncommon',
    stackable: false,
    maxStackSize: 1,
    tradeable: true,
    bindOnEquip: true,
    unlimited: false,
    salvageEssence: 5,
  },
  'tideback-fishing-rod': {
    id: 'tideback-fishing-rod',
    name: 'Tideback rod',
    flavorText: "Carved from driftwood that's weathered every tide the pond has thrown at it.",
    category: 'rod',
    rarity: 'rare',
    stackable: false,
    maxStackSize: 1,
    tradeable: true,
    bindOnEquip: true,
    unlimited: false,
    salvageEssence: 15,
  },
  'moonwater-fishing-rod': {
    id: 'moonwater-fishing-rod',
    name: 'Moonwater rod',
    flavorText: "The line seems to catch light that isn't there yet.",
    category: 'rod',
    rarity: 'epic',
    stackable: false,
    maxStackSize: 1,
    tradeable: true,
    bindOnEquip: true,
    unlimited: false,
    salvageEssence: 35,
  },
  'starlit-fishing-rod': {
    id: 'starlit-fishing-rod',
    name: 'Starlit rod',
    flavorText: 'Reels in starlight along with everything else.',
    category: 'rod',
    rarity: 'legendary',
    stackable: false,
    maxStackSize: 1,
    tradeable: true,
    bindOnEquip: true,
    unlimited: false,
    salvageEssence: 75,
  },
  'loot-box-common': {
    id: 'loot-box-common',
    name: 'Common Loot Box',
    flavorText: null,
    category: 'loot-box',
    stackable: true,
    maxStackSize: 9999,
    tradeable: true,
    bindOnEquip: false,
    unlimited: false,
    salvageEssence: 0,
  },
  'loot-box-uncommon': {
    id: 'loot-box-uncommon',
    name: 'Uncommon Loot Box',
    flavorText: null,
    category: 'loot-box',
    stackable: true,
    maxStackSize: 9999,
    tradeable: true,
    bindOnEquip: false,
    unlimited: false,
    salvageEssence: 0,
  },
  'loot-box-rare': {
    id: 'loot-box-rare',
    name: 'Rare Loot Box',
    flavorText: null,
    category: 'loot-box',
    stackable: true,
    maxStackSize: 9999,
    tradeable: true,
    bindOnEquip: false,
    unlimited: false,
    salvageEssence: 0,
  },
  'loot-box-epic': {
    id: 'loot-box-epic',
    name: 'Epic Loot Box',
    flavorText: null,
    category: 'loot-box',
    stackable: true,
    maxStackSize: 9999,
    tradeable: true,
    bindOnEquip: false,
    unlimited: false,
    salvageEssence: 0,
  },
  'loot-box-legendary': {
    id: 'loot-box-legendary',
    name: 'Legendary Loot Box',
    flavorText: null,
    category: 'loot-box',
    stackable: true,
    maxStackSize: 9999,
    tradeable: true,
    bindOnEquip: false,
    unlimited: false,
    salvageEssence: 0,
  },
  // Artifacts. Rarity, implicit and modifiers live on the instance; the server
  // rolls them on insert. Salvage pays scrap, so no Essence here.
  'artifact-cartographers-compass': {
    id: 'artifact-cartographers-compass',
    name: "Cartographer's Compass",
    flavorText: 'Its needle never points north. It points at whatever you were about to become.',
    category: 'artifact',
    stackable: false,
    maxStackSize: 1,
    tradeable: true,
    bindOnEquip: false,
    unlimited: false,
    salvageEssence: 0,
  },
  'artifact-ember-reliquary': {
    id: 'artifact-ember-reliquary',
    name: 'Ember Reliquary',
    flavorText: 'A coal that has not gone out since the Rift opened. Everything it touches remembers how to burn.',
    category: 'artifact',
    stackable: false,
    maxStackSize: 1,
    tradeable: true,
    bindOnEquip: false,
    unlimited: false,
    salvageEssence: 0,
  },
  'artifact-echoing-tuning-fork': {
    id: 'artifact-echoing-tuning-fork',
    name: 'Echoing Tuning Fork',
    flavorText: 'Strike it once and the Rift answers a beat late, and slightly louder.',
    category: 'artifact',
    stackable: false,
    maxStackSize: 1,
    tradeable: true,
    bindOnEquip: false,
    unlimited: false,
    salvageEssence: 0,
  },
  'artifact-wayfarers-anklet': {
    id: 'artifact-wayfarers-anklet',
    name: "Wayfarer's Anklet",
    flavorText: "Worn by a courier who outran the Rift's closing. She never did learn to stand still.",
    category: 'artifact',
    stackable: false,
    maxStackSize: 1,
    tradeable: true,
    bindOnEquip: false,
    unlimited: false,
    salvageEssence: 0,
  },
  'artifact-gluttons-kettle': {
    id: 'artifact-gluttons-kettle',
    name: "Glutton's Kettle",
    flavorText: 'The pond folk swear it is bottomless. It is, in the way that matters: nothing put in is ever wasted.',
    category: 'artifact',
    stackable: false,
    maxStackSize: 1,
    tradeable: true,
    bindOnEquip: false,
    unlimited: false,
    salvageEssence: 0,
  },
  scrap: {
    id: 'scrap',
    name: 'Scrap',
    flavorText: 'Buckles, bowstring and bent plate, carried back out of the dark.',
    category: 'material',
    rarity: 'common',
    stackable: true,
    maxStackSize: 9999,
    tradeable: false,
    bindOnEquip: false,
    unlimited: false,
    salvageEssence: 0,
  },
  timber: {
    id: 'timber',
    name: 'Timber',
    flavorText: 'Felled at the edge of the firelight and stacked to season.',
    category: 'material',
    rarity: 'common',
    stackable: true,
    maxStackSize: 9999,
    tradeable: false,
    bindOnEquip: false,
    unlimited: false,
    salvageEssence: 0,
  },
  stone: {
    id: 'stone',
    name: 'Stone',
    flavorText: 'Cut from the hillside behind the camp, still cold from the ground.',
    category: 'material',
    rarity: 'common',
    stackable: true,
    maxStackSize: 9999,
    tradeable: false,
    bindOnEquip: false,
    unlimited: false,
    salvageEssence: 0,
  },
  'rift-shard': {
    id: 'rift-shard',
    name: 'Rift shard',
    flavorText: 'A splinter of the Abyss, humming faintly. It never quite settles in the hand.',
    category: 'material',
    rarity: 'rare',
    stackable: true,
    maxStackSize: 9999,
    tradeable: false,
    bindOnEquip: false,
    unlimited: false,
    salvageEssence: 0,
  },
  roe: {
    id: 'roe',
    name: 'Roe',
    flavorText: 'Taken from a fish that will not be swimming again. The smokehouse asks for it by the handful.',
    category: 'material',
    rarity: 'common',
    stackable: true,
    maxStackSize: 9999,
    tradeable: false,
    bindOnEquip: false,
    unlimited: false,
    salvageEssence: 0,
  },
} as const satisfies Record<string, InventoryItemDefinition>

export type KnownInventoryItemDefinitionId = keyof typeof INVENTORY_ITEM_DEFINITIONS

export const ALL_INVENTORY_ITEM_DEFINITIONS: readonly InventoryItemDefinition[] =
  Object.values(INVENTORY_ITEM_DEFINITIONS)

export function isInventoryItemDefinitionId(
  value: unknown,
): value is string {
  return typeof value === 'string' && INVENTORY_ITEM_ID_PATTERN.test(value)
}

export function isInventoryItemCategory(
  value: unknown,
): value is InventoryItemCategory {
  return value === 'fish' ||
    value === 'bait' ||
    value === 'rod' ||
    value === 'loot-box' ||
    value === 'artifact' ||
    value === 'material' ||
    value === 'utility'
}

export function getInventoryItemDefinition(
  definitionId: string,
): InventoryItemDefinition | undefined {
  return isInventoryItemDefinitionId(definitionId)
    ? INVENTORY_ITEM_DEFINITIONS[definitionId as KnownInventoryItemDefinitionId]
    : undefined
}
