create table public.bug_reports (
  id bigint generated by default as identity primary key,
  user_id uuid not null default (auth.uid()) references auth.users (id) on delete cascade,
  submitted_at timestamptz not null default now(),
  bug text not null check (char_length(trim(bug)) > 0),
  image_data text,
  image_name text,
  image_type text,
  dungeon_info jsonb not null
);

alter table public.bug_reports enable row level security;

create policy "Bug reports are insertable by their owner"
on public.bug_reports
for insert
to authenticated
with check ((select auth.uid()) = user_id);

grant insert on table public.bug_reports to authenticated;
grant usage, select on sequence public.bug_reports_id_seq to authenticated;
